{
    "name": "Glassify Theme",
    "summary": "Glassify Backend Theme [Alpha version]",
    "version": "18.0.1.0.0",
    "category": "Themes/Backend",
    "license": "LGPL-3",
    "author": "Openworx",
    "website": "https://www.openworx.nl",
    'images': ['images/screenshot.png'],
    "depends": ["web_responsive", "base_setup"],
    "installable": True,
    "auto_install": False,
    "application": False,
    "data": [
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            (
                "after",
                "web_responsive/static/src/legacy/scss/primary_variable.scss",
                "glassify_theme/static/src/scss/primary_variables.scss",
            ),
        ],
        "web.assets_backend": [
            "glassify_theme/static/src/scss/_mixins.scss",
            "glassify_theme/static/src/scss/_utilities.scss",
            "glassify_theme/static/src/scss/_navbar.scss",
            "glassify_theme/static/src/scss/_control_panel.scss",
            "glassify_theme/static/src/scss/_sidebar.scss",
            "glassify_theme/static/src/scss/_apps_menu.scss",
            "glassify_theme/static/src/scss/_cards.scss",
            "glassify_theme/static/src/scss/_forms.scss",
            "glassify_theme/static/src/scss/_modals.scss",
            "glassify_theme/static/src/scss/_kanban.scss",
            "glassify_theme/static/src/scss/_list_view.scss",
            "glassify_theme/static/src/scss/_calendar.scss",
            "glassify_theme/static/src/scss/_sidebar_menu.scss",
            "glassify_theme/static/src/scss/glassify.scss",
            "glassify_theme/static/src/js/sidebar_menu.esm.js",
            "glassify_theme/static/src/xml/sidebar_menu.xml",
        ],
    },
    "sequence": 2,
}
